name: manifest

on:
  push:
    branches: [ main ]

jobs:
  publish:
    if: "!startsWith(github.event.head_commit.message, 'chore')"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "asdf-vm/actions/install@v1"
    - uses: "actions/cache@v2"
      with:
        path: |
          ~/.yarn
          manifest/.spago
          manifest/output
          manifest/node_modules
        key: always-lol
    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
    - run: "yarn"
      working-directory: "manifest"
    - run: "yarn gen-manifest"
      working-directory: "manifest"
    - run: |
        git add -A
        git commit -m 'chore: update manifest' && git push || echo 'manifest unchanged'
