name: manifest

on:
  push:
    branches: [ main ]

jobs:
  publish:
    if: "!startsWith(github.event.head_commit.message, 'chore')"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "asdf-vm/actions/install@v1"
    - uses: "actions/cache@v2"
      with:
        path: |
          ~/.yarn
          ~/.asdf
          manifest/output
          manifest/node_modules
        key: ${{runner.os}}-node-${{hashFiles('**/yarn.lock')}}
        restore-keys: ${{runner.os}}-node-14
    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
    - run: "yarn && yarn start"
      working-directory: "manifest"
    - run: "git add -A"
    - run: "git commit -m 'chore: update manifest'"
    - run: "git push"
